### ISSUE TITLE
Investigate usage in GitHub actions

### ISSUE THREAD

**Issue by xstefank** [jboss/tyr#141]
If tyr wouldn't need to run as a standalone service we could use it directly in the github actions for a particular PR.

**Comment by xstefank** [comment]
@petrberan please post here your findings.

**Comment by petrberan** [comment]
It is possible to use github actions for Tyr standlaone. This action

```
name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  printJob:    
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github.event) }}
      run: |
        echo "$GITHUB_CONTEXT"
```
lists webhook event json after creating (_opened_) and reopening (_reopened_) PR, editing PR description or PR title (_edited_) or if new commit is pushed or force pushed (_synchronize_)
